# SITE CONFIGURATION
title: Zhun's Blog.with(sysDev); # your site title
author: Jihun Park # You :P
description: > # Meta description of Homepage
  The best programmers
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jihunparkme.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Jihun Park
    - https://github.com/jihunparkme
    - https://www.instagram.com/zzzzhunp/
    - https://data-make.tistory.com/

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
 # - {name: 'Contact', link: '/contact'}
  - {name: 'Categories', link: '/categories'}
  - {name: 'Search', link: '/search'}

tagline: >
   Non mollare
hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: jihunpark.tech@gmail.com # email for form submission

twitter_username:  # replace with your_twitter_username or comment to remove link from footer
github_username:  jihunparkme # replace with your_github_username or comment to remove link from footer
instagram_username: zzzzhunp # replace with your_instagram_username or comment to remove link from footer
tistory_username: data-make

disqus:
  shortname: jihunparkme # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag